name: find_kajian
description: A new Flutter project.
publish_to: "none"
version: 1.2.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  equatable: ^2.0.5
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hijri: ^3.0.0
  injectable: ^2.4.4
  intl: ^0.19.0
  package_info_plus: ^8.0.1
  permission_handler: ^11.2.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^25.1.35
  url_launcher: ^6.1.6
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/svg/
    - assets/splash_image.png
